import { INodeProperties } from 'n8n-workflow';

export const listOperations: INodeProperties[] = [
  { displayName: 'Operation', name: 'operation', type: 'options', noDataExpression: true,
    displayOptions: { show: { resource: ['list'] } },
    options: [
      { name: 'List Centre', value: 'listCentre', action: 'List Centre' },
      { name: 'List Activity', value: 'listActivity', action: 'List Activity' },
      { name: 'List Cash', value: 'listCash', action: 'List Cash' },
      { name: 'List Cash Register', value: 'listCashRegister', action: 'List Cash Register' },
      { name: 'List Bank Account', value: 'listBankAccount', action: 'List Bank Account' },
      { name: 'List Accounting Single Entry', value: 'listAccountingSingleEntry', action: 'List Accounting Single Entry' },
      { name: 'List Accounting Double Entry', value: 'listAccountingDoubleEntry', action: 'List Accounting Double Entry' },
      { name: 'List Account', value: 'listAccount', action: 'List Account' },
      { name: 'List Numeric Series', value: 'listNumericSeries', action: 'List Numeric Series' },
      { name: 'Create Accounting Double Entry', value: 'createAccountingDoubleEntry', action: 'Create Accounting Double Entry' },
      { name: 'List Invoice', value: 'listInvoice', action: 'List Invoice' },
      { name: 'List Int Doc', value: 'listIntDoc', action: 'List Int Doc' },
      { name: 'List Prodejka', value: 'listProdejka', action: 'List Prodejka' },
      { name: 'List Vyroba', value: 'listVyroba', action: 'List Vyroba' },
      { name: 'List Prevodka', value: 'listPrevodka', action: 'List Prevodka' },
      { name: 'List Voucher', value: 'listVoucher', action: 'List Voucher' },
      { name: 'List Order', value: 'listOrder', action: 'List Order' },
      { name: 'List Enquiry', value: 'listEnquiry', action: 'List Enquiry' },
      { name: 'List Offer', value: 'listOffer', action: 'List Offer' },
      { name: 'List Parameter', value: 'listParameter', action: 'List Parameter' },
      { name: 'List User Code', value: 'listUserCode', action: 'List User Code' },
      { name: 'List Vydejka', value: 'listVydejka', action: 'List Vydejka' },
      { name: 'List Prijemka', value: 'listPrijemka', action: 'List Prijemka' },
      { name: 'List Storage', value: 'listStorage', action: 'List Storage' },
      { name: 'List Selling Price', value: 'listSellingPrice', action: 'List Selling Price' },
      { name: 'List Balance', value: 'listBalance', action: 'List Balance' },
      { name: 'List Category', value: 'listCategory', action: 'List Category' },
      { name: 'List Int Param', value: 'listIntParam', action: 'List Int Param' },
      { name: 'List Individual Price', value: 'listIndividualPrice', action: 'List Individual Price' },
      { name: 'List Supplier', value: 'listSupplier', action: 'List Supplier' },
      { name: 'List Accountancy', value: 'listAccountancy', action: 'List Accountancy' },
      { name: 'List Bank', value: 'listBank', action: 'List Bank' },
      { name: 'List Store', value: 'listStore', action: 'List Store' },
      { name: 'List Group Stocks', value: 'listGroupStocks', action: 'List Group Stocks' },
      { name: 'List Action Price', value: 'listActionPrice', action: 'List Action Price' },
      { name: 'List Inventory Lists', value: 'listInventoryLists', action: 'List Inventory Lists' },
      { name: 'List Payment', value: 'listPayment', action: 'List Payment' },
      { name: 'List Numerical Series', value: 'listNumericalSeries', action: 'List Numerical Series' },
      { name: 'List G D P R', value: 'listGDPR', action: 'List G D P R' },
      { name: 'List Establishment', value: 'listEstablishment', action: 'List Establishment' },
      { name: 'List Accounting Form Of Payment', value: 'listAccountingFormOfPayment', action: 'List Accounting Form Of Payment' },
      { name: 'List Classification V A T', value: 'listClassificationVAT', action: 'List Classification V A T' },
      { name: 'List Global Settings', value: 'listGlobalSettings', action: 'List Global Settings' },
      { name: 'List Registration Number', value: 'listRegistrationNumber', action: 'List Registration Number' },
      { name: 'List Product Requirement', value: 'listProductRequirement', action: 'List Product Requirement' },
      { name: 'List Movement', value: 'listMovement', action: 'List Movement' },
      { name: 'List Recycling Contrib', value: 'listRecyclingContrib', action: 'List Recycling Contrib' },
      { name: 'List Service', value: 'listService', action: 'List Service' },
      { name: 'List Rules Pairing', value: 'listRulesPairing', action: 'List Rules Pairing' },
      { name: 'List User Agenda', value: 'listUserAgenda', action: 'List User Agenda' },
      { name: 'List Contract', value: 'listContract', action: 'List Contract' },
      { name: 'List User Code Pack', value: 'listUserCodePack', action: 'List User Code Pack' },
    ], default: 'listCentre' },
];

export const listFields: INodeProperties[] = [
  // TODO: add fields for list operations
];
